#######################
# Dwarf Wars Settings #
#######################

# Log Settings
[Log Settings]
LogFileName="log.log"
LogPollRate=60000 # in miliseconds
LogPath="./logs"
LogMaxSize = 5 # in megabytes

[Server Settings]
Address="0.0.0.0"
Port=3000
Idle_Timeout=1000 # miliseconds
