version: '3.1'

services:

  db:
    image: mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - sql-data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: "password"
volumes:
  sql-data:
    driver: local
    external: false
