Services:
  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - sql-data:/var/lib/mysql
  app:
    image:
      build: .
    ports:
      - "3000:3000"
    volumes:
      - ./pkg/:/usr/app/pkg
      - ./cmd/:/usr/app/cmd
network:
  app
volumes:
  sql-data:
    driver: local
    external: false
