#######################
# Dwarf Wars Settings #
#######################

["Log Settings"]
"Max Size" = 5 # Megabytes
"File Name" = "log.log"
Path = "./logs/"

["Game Server"]
Address = ""
Port = 3_000
"Idle Timeout" = 300 # Miliseconds


#####################################
## AUTHENTICANTION DATABASE SERVER ##
#####################################
["Database Servers".Auth]
Address = "localhost"
Port = 3306
Driver = "mysql"
Trusted = false
Username = "root"
Password = "password"
"DB" = "USERS"
Views = { }

[["Database Servers".Auth.Tables.User_Login]]
Name = "UID"
Type = "VARCHAR(100)"
"Auto Increment" = false
"Primary Key" = true
"Foriegn Key" = false
"Null Allowed" = false

[["Database Servers".Auth.Tables.User_Login]]
Name = "Secret"
Type = "VARCHAR(100)"
"Auto Increment" = false
"Primary Key" = false
"Foriegn Key" = false
"Null Allowed" = false

[["Database Servers".Auth.Tables.User_Login]]
Name = "Last_Seen"
Type = "datetime"
"Auto Increment" = false
"Primary Key" = false
"Foriegn Key" = false
"Null Allowed" = true

[["Database Servers".Auth.Tables.User_Login]]
Name = "Creation_Timestamp"
Type = "datetime"
"Auto Increment" = false
"Primary Key" = false
"Foriegn Key" = false
"Null Allowed" = false
Default = "CURRENT_TIMESTAMP()"

[["Database Servers".Auth.Tables.Access_Logs]]
Name = "UID"
Type = "VARCHAR(100)"
"Auto Increment" = false
"Primary Key" = true
"Foriegn Key" = false
"Null Allowed" = false


############################
## Game States SQL Server ##
############################
["Database Servers".Stats]
Address = "localhost"
Port = 3306
Driver = "mysql"
Trusted = false
Username = "root"
Password = "password"
"DB" = "GAME_STATS"
Views = { }

[["Database Servers".Stats.Tables.Match_Events]]
Name = "Match_ID"
Type = "VARCHAR(255)"
"Auto Increment" = false
"Primary Key" = false
"Foriegn Key" = false
"Null Allowed" = false

[["Database Servers".Stats.Tables.Match_Events]]
Name = "UID"
Type = "VARCHAR(100)"
"Auto Increment" = false
"Primary Key" = false
"Foriegn Key" = false
"Null Allowed" = true

[["Database Servers".Stats.Tables.Match_Events]]
Name = "Event"
Type = "LONGTEXT"
"Auto Increment" = false
"Primary Key" = false
"Foriegn Key" = false
"Null Allowed" = false

[["Database Servers".Stats.Tables.Chat_Logs]]
Name = "ID"
Type = "INTEGER"
"Auto Increment" = true
"Primary Key" = true
"Foriegn Key" = false
"Null Allowed" = false

[["Database Servers".Stats.Tables.Chat_Logs]]
Name = "Match_ID"
Type = "VARCHAR(255)"
"Auto Increment" = false
"Primary Key" = false
"Foriegn Key" = false
"Null Allowed" = false

[["Database Servers".Stats.Tables.Chat_Logs]]
Name = "UID"
Type = "VARCHAR(100)"
"Auto Increment" = false
"Primary Key" = false
"Foriegn Key" = false
"Null Allowed" = false

[["Database Servers".Stats.Tables.Chat_Logs]]
Name = "Message"
Type = "TEXT"
"Auto Increment" = false
"Primary Key" = false
"Foriegn Key" = false
"Null Allowed" = true


##########################
## Game Data SQL Server ##
##########################
["Database Servers".Game]
Address = "localhost"
Port = 3306
Username = "root"
Password = "password"
Driver = "mysql"
Trusted = false
"DB" = "GAME_DATA"
Views = { }

  ["Database Servers".Game.Tables]
  Archived_Games = [ ]

    [["Database Servers".Game.Tables.Games]]
    Name = "Match_ID"
    Type = "VARCHAR(255)"
    "Auto Increment" = false
    "Primary Key" = true
    "Foriegn Key" = false
    "Null Allowed" = false

    [["Database Servers".Game.Tables.Games]]
    Name = "Length"
    Type = "INTEGER"
    "Auto Increment" = false
    "Primary Key" = false
    "Foriegn Key" = false
    "Null Allowed" = true

