[General_Settings]
FullScreen = false
# LQ  |  480p - 720x480
# HD  |  720p - 1280x720
# FHD | 1080p - 1920x1080
# 2K  | 1440p - 2560x1440
# 4K  | 2160p - 3840x2160
# 8K  | 4320p - 7680x4320
Screen_Width = 2560
Screen_Height = 1440 
FPS = 60
Default_Font = "AlmendraSC-Regular.ttf"
Default_Font_Size = 100 # Height in pixels
Default_Font_Resolution = 400
Default_Font_Spacing = 0

[Network_Settings]
Address = "127.0.0.1"
Connection_Timeout = 5000
Port = 3_000
Buffer_Size = 1_024

[Logging_Settings]
