[General_Settings]
FullScreen = false
Screen_Width = 800
Screen_Height = 450
Default_Font = "AlmendraSC-Regular.ttf"
Default_Font_Size = 100 # Height in pixels
Default_Font_Resolution = 400

[Network_Settings]
Address = "127.0.0.1"
Connection_Timeout = 5000
Port = 3_000
Buffer_Size = 1_024

[Logging_Settings]
