[Logging]
Size                = 5  # MB
Max_Age		    = 10 # days
Backups 	    = 5
Compression    	    = false
Name                = "log.log"
Path                = "./logs/"
Prefix              = "Server: "

[Logging.Flags]
UTC          = false
Date         = true
Time         = true
Longfile     = false
Msgprefix    = false
Shortfile    = true
Microseconds = false

["Game Server"]
Address = ""
Port = 3_000

["Game Server".Timeouts]
Idle  = 300 # Miliseconds
Read  = 300 # Miliseconds
Write = 300 # Miliseconds


[DB]
BaseDir = "./databases/"
#Password = "123"
Querries_Dir ="./sql/"
