#######################################
## Dwarf Wars Authentication Databse ##
#######################################
[[Databases]]
Name = "AUTH"
Address = "localhost"
Port = 3306
Driver = mysql
Trusted = false
Username = "root"
Password = "password"
Views = {}
Tables = {}

## USER_LOGIN TABLE ##
[[Databases.Tables.USER_LOGIN]]
Name = "UID"
Type = "VARCHAR(100)"
"Auto Increment" = false
"Primary Key" = true
"Foriegn Key" = false
"Null Allowed" = false

[[Databases.Tables.USER_LOGIN]]
Name = "SECRET"
Type = "VARCHAR(100)"
"Auto Increment" = false
"Primary Key" = false
"Foriegn Key" = false
"Null Allowed" = false

[[Databases.Tables.USER_LOGIN]]
Name = "LAST_SEEN"
Type = "datetime"
"Auto Increment" = false
"Primary Key" = false
"Foriegn Key" = false
"Null Allowed" = true

[[Databases.Tables.USER_LOGIN]]
Name = "CREATE_TIME"
Type = "datetime"
"Auto Increment" = false
"Primary Key" = false
"Foriegn Key" = false
"Null Allowed" = false
Default = "CURRENT_TIMESTAMP()"

## ACCESS_LOGS TABLE ##
[[Databases.Tables.ACCESS_LOGS]]
Name = "UID"
Type = "VARCHAR(100)"
"Auto Increment" = false
"Primary Key" = false
"Foriegn Key" = false
"Null Allowed" = false

[[Databases.Tables.ACCESS_LOGS]]
Name = "TIMESTAMP"
Type = "datetime"
"Auto Increment" = false
"Primary Key" = false
"Foriegn Key" = false
"Null Allowed" = false

[[Databases.Tables.ACCESS_LOGS]]
Name = "ADDRESS" # IP
Type = "VARCHAR(100)"
"Auto Increment" = false
"Primary Key" = false
"Foriegn Key" = false
"Null Allowed" = false

[[Databases.Tables.ACCESS_LOGS]]
Name = "RECIEVED_REQUEST"
Type = "LONGTEXT"
"Auto Increment" = false
"Primary Key" = false
"Foriegn Key" = false
"Null Allowed" = false

####################################
## Dwarf Wars Game Stats Database ##
####################################
[[Databases]]
Name = "STATS"
Address = "localhost"
Port = 3306
Driver = mysql
Trusted = false
Username = "root"
Password = "password"
Views = {}

## MATCH_EVENT Table ##
[[Databases.Tables.MATCH_EVENTS]]
Name = "MATCH_ID"
Type = "VARCHAR(100)"
"Auto Increment" = false
"Primary Key" = false
"Foriegn Key" = false
"Null Allowed" = false

[[Databases.Tables.MATCH_EVENTS]]
Name = "UID"
Type = "VARCHAR(100)"
"Auto Increment" = false
"Primary Key" = false
"Foriegn Key" = false
"Null Allowed" = true


[[Databases.Tables.MATCH_EVENTS]]
Name = "EVENT"
Type = "LONGTEXT"
"Auto Increment" = false
"Primary Key" = false
"Foriegn Key" = false
"Null Allowed" = false

## CHAT_LOGS Table ##
[[Databases.Tables.CHAT_LOGS]]
Name = "Match_ID"
Type = "VARCHAR(100)"
"Auto Increment" = false
"Primary Key" = false
"Foriegn Key" = false
"Null Allowed" = false

[[Databases.Tables.CHAT_LOGS]]
Name = "UID"
Type = "VARCHAR(100)"
"Auto Increment" = false
"Primary Key" = false
"Foriegn Key" = false
"Null Allowed" = false

[[Databases.Tables.CHAT_LOGS]]
Name = "MESSAGE"
Type = "TEXT"
"Auto Increment" = false
"Primary Key" = false
"Foriegn Key" = false
"Null Allowed" = false

######################################
## Dwarf Wars Active Games Database ##
######################################
[[Databases]]
Name = "GAME"
Address = "localhost"
Port = 3306
Driver = mysql
Trusted = false
Username = "root"
Password = "password"
Views = {}
Tables = {}

## ACTIVE_GAMES Table ##
[[Databases.Tables.ACTIVE_GAMES]]
Name = "Match_ID"
Type = "VARCHAR(100)"
"Auto Increment" = false
"Primary Key" = true
"Foriegn Key" = false
"Null Allowed" = false

[[Databases.Tables.ACTIVE_GAMES]]
Name = "Length"
Type = "INTEGER"
"Auto Increment" = false
"Primary Key" = false
"Foriegn Key" = false
"Null Allowed" = false

## ARCHIVED_GAMES Table ##
[[Databases.Tables.ARCHIVED_GAMES]]
Name = "Match_ID"
Type = "VARCHAR(100)"
"Auto Increment" = false
"Primary Key" = true
"Foriegn Key" = false
"Null Allowed" = false
