[Logging]
Size                = 5         # MB
Name                = "log.log" # Name of file to push logs to
Path                = "./logs/" # Path for the above file is located
Prefix              = "Server: "

[Logging.Flags]
UTC          = false
Date         = true
Time         = true
Longfile     = false
Msgprefix    = false
Shortfile    = true
Microseconds = false

["Game Server"]
Address = ""
Port = 3_000

["Game Server".Timeouts]
Idle  = 300 # Miliseconds
Read  = 300 # Miliseconds
Write = 300 # Miliseconds


[DB]
"Server Address" = "127.0.0.1"
"Server Port" = 3306
# going to put this in a more secure location later on
"Server Username" = "root"
"Server Password" = "password"
####
"Validation Direcroty" = "./config/sql/validation/"
